---
ansible_user: "meow"
ansible_user_dir: "/home/{{ ansible_user }}"
config_base_path: "/gitrepos/OS-SETUP-FINAL/config/"

repos:
  - name: "bash"
    repo_url: "git@github.com:DavidJohannesS/bash.git"
    links:
      - src: "{{ config_base_path }}/bash/.bashrc"
        dest: "{{ ansible_user_dir }}/.bashrc"
      - src: "{{ config_base_path }}/bash/.bash_aliases"
        dest: "{{ ansible_user_dir }}/.bash_aliases"

  - name: "dunst"
    repo_url: "git@github.com:DavidJohannesS/dunst.git"
    links:
      - src: "{{ config_base_path }}/dunst/dunstrc"
        dest: "{{ ansible_user_dir }}/.config/dunst/dunstrc"

  - name: "fonts"
    repo_url: "git@github.com:DavidJohannesS/fonts.git"
    links:
      - src: "{{ config_base_path }}/fonts/FiraCode-Bold.ttf"
        dest: "/usr/share/fonts/FiraCode-Bold.ttf"

  - name: "git"
    repo_url: "git@github.com:DavidJohannesS/git.git"
    links:
      - src: "{{ config_base_path }}/git/.gitconfig"
        dest: "{{ ansible_user_dir }}/.gitconfig"

  - name: "i3"
    repo_url: "git@github.com:DavidJohannesS/i3.git"
    links:
      - src: "{{ config_base_path }}/i3/config"
        dest: "{{ ansible_user_dir }}/.config/i3/config"

  - name: "nvim"
    repo_url: "git@github.com:DavidJohannesS/nvim.git"
    links:
      - src: "{{ config_base_path }}/nvim/nvim"
        dest: "{{ ansible_user_dir }}/.config/nvim"

  - name: "picom"
    repo_url: "git@github.com:DavidJohannesS/picom.git"
    links:
      - src: "{{ config_base_path }}/picom/picom.conf"
        dest: "{{ ansible_user_dir }}/.config/picom.conf"

  - name: "polybar"
    repo_url: "git@github.com:DavidJohannesS/polybar.git"
    links:
      - src: "{{ config_base_path }}/polybar/polybar"
        dest: "{{ ansible_user_dir }}/.config/polybar"

  - name: "rofi"
    repo_url: "git@github.com:DavidJohannesS/rofi.git"
    links:
      - src: "{{ config_base_path }}/rofi/rose-pine.rasi"
        dest: "{{ ansible_user_dir }}/.config/rofi/config.rasi"

  - name: "tmux"
    repo_url: "git@github.com:DavidJohannesS/tmux.git"
    links:
      - src: "{{ config_base_path }}/tmux/.tmux.conf"
        dest: "{{ ansible_user_dir }}/.tmux.conf"

  - name: "tools"
    repo_url: "git@github.com:DavidJohannesS/tools.git"
    links:
      - src: "{{ config_base_path }}/tools/tools"
        dest: "{{ ansible_user_dir }}/tools"
