---
# tasks file for DotFM
- name: Setup DotFM
  ansible.builtin.include_tasks: setup.yml

- name: Link files
  ansible.builtin.include_tasks: symlink.yml

- name: Setup Lightdm
  ansible.builtin.include_tasks: lightdm.yml
### ---------------------------------- ###
# Utility
- name: Push to git
  ansible.builtin.include_tasks: commit_push.yml
  tags:
    - never
    - gcp

- name: Enable unit files
  ansible.builtin.include_tasks: sysdMounts.yml
  tags:
    - never
    - sysd
- name: Pull latest config
  ansible.builtin.include_tasks: pull_latest.yml
  tags:
    - never
    - pull
