---
# tasks file for DotFM
- name: Setup DotFM
  ansible.builtin.include_tasks: setup.yml

- name: Link files
  ansible.builtin.include_tasks: symlink.yml


### ---------------------------------- ###
# Utility
- name: Push to git
  ansible.builtin.include_tasks: commit_push.yml
  tags:
    - never
    - commit_push_all_branches
