---
- name: Commit changes in worktree
  ansible.builtin.shell: |
    git add . &&
    git commit -m "DotFM Update"
  args:
    chdir: "{{ worktree_path }}/{{ item.branch_dir }}"
  with_items: "{{ branch_dirs }}"
  ignore_errors: true
  loop_control:
    label: "{{ worktree_path }}/{{ item.branch_dir }}"

- name: Push changes to remote
  ansible.builtin.command:
    cmd: git push origin "{{ item.branch_dir }}"
    chdir: "{{ worktree_path }}/{{ item.branch_dir }}"
  with_items: "{{ branch_dirs }}"
  loop_control:
    label: "{{ worktree_path }}/{{ item.branch_dir }}"
